openapi: 3.0.3
info:
  title: Species on the US National Parks API
  description: |-
    This API exposes a dataset on biodiversity in the US National Park. 
    The original file was published by the National Park service on Kaggle.
    
    Link to the original source of the dataset:
    [Kaggle](https://www.kaggle.com/datasets/nationalparkservice/park-biodiversity)

    The dataset contains entries on the species present on the US National Parks.
    
    You can find additional information on:
    * [US National Parks Service](https://www.nps.gov/index.htm)
    * [Biodiversity on Wikipedia](https://en.wikipedia.org/wiki/Biodiversity)
  contact:
    email: ona.tarrago@gmail.com
  license:
    name: CC BY 4.0 International
    url: https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1
  version: 1.0.0
paths:
  /species/{species_id}:
    get:
      summary: Get a species by its ID.
      description: Return all the information on the species.
      parameters:
        - name: species_id
          in: path
          description: ID of the species
          example: ACAD-1000
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/species_id'          
        '404':
          description: Species not found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - api_auth: []
  /species:
    get:
      summary: Get all species
      description: Return all the information about all the species.
      parameters:
        - name: page
          in: query
          example: 0
          description: Index of the page (used for pagination)
          schema:
            type: integer
        - name: page_size
          in: query
          example: 100
          description: Number of species per page (used for pagination)
          schema:
            type: integer
        # - name: include_details
        #   in: query
        #   example: 0
        #   description: Whether or not to include people and genres (0 or 1)
        #   schema:
        #     type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  species:
                    type: array
                    items:
                      $ref: '#/components/schemas/species'
                  next_page:
                    type: integer
                    example: 0
                  last_page:
                    type: integer
                    example: 1000
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
    components:
      schemas:
        species:
          type: object
          properties:
            id:
              type: string
              description: The unique identifier of the species
          required:
            - id
      
      security:
        - api_auth: []          
  securitySchemes:
    api_auth:
      type: http
      scheme: basic
      description: Please authenticate to use the API